gui:
  showIcons: true

git:
  branchLogCmd: "git log --oneline --all --graph --decorate --color=always"

keybinding:
    universal:
      return: 'q' # default was esc
      quit: 'Q' # default was q
