# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[shell]
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user ]($style)'
disabled = false
show_always = true

 [os]
format = "on [($name )]($style)"
style = "bold blue"
disabled = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

[directory]
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
time_format = '%T'

