# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname$shell$shlvl \
$directory \
$git_branch$git_status\
$character\
"""
right_format = """
$all\
$java $gradle \
$time\
"""

add_newline = true  # default is true

[hostname]
format = '[$ssh_symbol](bold green)[$hostname](blue)'
disabled = false
ssh_only = false

[shell]
format = "[](cyan)[$indicator](blue)"
bash_indicator = "bash"
disabled = false

[shlvl]
format = "[x$shlvl]($style)"
threshold = 3
disabled = false

[directory]
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false
format = "[$path](white)"
home_symbol = " "

[git_branch]
format = '[ $branch(:$remote_branch)](yellow) '

[git_status]
style = "yellow"

[character]
error_symbol = "[❯❯](green)" # for git status
success_symbol = "[❯❯](green)"

[cmd_duration]
disabled = true

[aws]
format = '[$symbol](dimmed green)'
symbol = " "
disabled = true

[java]
format = '[${symbol}(${version} )](dimmed bright-cyan)'
symbol = " "
version_format = '${raw}'

[gradle]
format = '[${symbol}(${version} )](dimmed bright-cyan)'
symbol = ' '
version_format = '${raw}'

[time]
time_format = '%T'
format = "[$time]($style)"
style = "dimmed green"
disabled = false

[username]
disabled = true

