# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username \
$shell\
$directory\
$git_branch$git_status\
$character\
"""
right_format = "$all$time $os $hostname"


add_newline = true  # default is true

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red) '
disabled = false

 [os]
format = "[$name]($style)"
style = "bold blue"
disabled = false

[directory]
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false
format = "[$path ]($style)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[time]
disabled = false
time_format = '%T'
format = "[$time]($style)"

[shell]
disabled = false

[character]
error_symbol = "[❯❯](bold green)" # for git status
success_symbol = "[❯❯](bold green)"

