name: Docker Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run container
        run: |
          docker build -t my-devenv .
          docker run my-devenv
